give @p nacal_tac:elesmoke 16
give @p nacal_tac:mimictac 16
give @p nacal_tac:normal 16
give @p nacal_tac:nuke 16
give @p nacal_tac:healarea 16
give @p nacal_tac:transport 16
give @p nacal_tac:mineset 16
give @p nacal_tac:blow 16
give @p nacal_tac:shellraid 16
give @p nacal_tac:force 16
give @p nacal_tac:detect 16
give @p nacal_tac:raid 16
give @p nacal_tac:light 16
give @p nacal_tac:smoke 16
give @p nacal_tac:flash 16
give @p nacal_tac:flame 16
